version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: my_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypass
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
